### ISSUE TITLE
为什么用这个？

### ISSUE THREAD

**Issue by sky-admin** [upcyiban/upc-info#1]
这好像是部署到GitHub page上的吧？速度很慢啊。咱自己的服务器没了吗？
API服务在咱自己的服务器上吧？用HTTPS了吗？gh-page是HTTPS站不能XHR请求非HTTPS站哦。

**Comment by sky-admin** [comment]
markdown换行是`两个空格`，看看[这个项目]( https://github.com/guodongxiaren/README)了解下MD吧，写文档很有帮助。

**Comment by wanghaojun** [comment]
用这个是因为大二的觉得这个比较方便，咱们服务器现在还在，还能用。
现在的API文档用的是swagger ui。

**Comment by sky-admin** [comment]
那速度慢和能否调用接口的问题如何解决？我觉得可以考虑升级一波HTTPS。

**Comment by 1409070209** [comment]
老部长，你好。以前的前端架构已经不支持我部业务的迭代。这是您疑问的简单回答。
更详细的理由如下。
1:前端工程化。  使用单一的技术栈能方便工程化的进度，并能方便组织交流。也不会因为学弟们喜欢react而放弃进入易班。因为他们什么都不会。


2.逻辑抽离。    每一个轻应用都需要想yiban做token，这是开发轻应用最麻烦的。将开发者的精力集中到业务本身可以降低门槛，比如上一次的轻应用比赛就因为门槛高没有报名。
大量的轻应用将引入埋点。将用户的操作上传到服务器当场前端的logger。并且引入线上测试功能，在已经部署上以后在localstorage里面引入测试的开关，从而开启console.log

这些功能都是通用功能，旧有的架构不能支持改业务的发展

3更强的性能。。   旧项目杂乱有些没有经过打包就部署上线，项目质量难以监督，使用统一的工程可以方便的做异步路由化或以后引入ssr做seo优化。


为什么使用vue
1vue门槛简单，向下兼容更强，非单向的数据流也方便学习。
2vue-cli脚手架自带了edit配置，方便为项目配置统一的缩进
3更简单的异步路由
4react的样式组件化需要引入style component这个额外的框架

以后也会开启react的项目

**Comment by sky-admin** [comment]
不，我问的不是为什么用vue……不用这么严肃的……我的问题是，为什么用GitHub page来部署而不是咱自己的服务器，调用接口会不会有问题，是否有demo已经试过了？你这些理由写得都不错，挺棒的，后面可以再多想想git规范和自动化测试、上线。

**Comment by 1409070209** [comment]
GitHub page部署一边，没有BUG在正式部署上线。以前的项目没有GitHub page，或者同学们不知道怎么配，需要上线后测试，所以在这个git上先部署一遍，没有BUG就可以上去了。我们的服务器还能用

**Comment by sky-admin** [comment]
规范流程之类的可以参考一下这个项目：https://github.com/zzuu666/antue ，看看对你们有没有启发，这是我跟朋友合作的一个项目，正在进行中，你们有兴趣也是可以参与进来，难度并不算很大。可以看看我们的一些规范：主要集中在git规范，PR审核，Travis持续集成。

**Comment by sky-admin** [comment]
相当于一个预览机环境？可以。那如果这个应用有调用API的需要呢？能调吗？

**Comment by 1409070209** [comment]
如果后端已经上线，那么GitHub page是可以调这个接口的，没有部署上线需要本地运行并且做内网穿透。内网穿透我过几天给贴个教程

**Comment by sky-admin** [comment]
API已经用上HTTPS了吗？

**Comment by 1409070209** [comment]
没有用HTTPS。我过几天测试一下GitHub page

**Comment by sky-admin** [comment]
HTTPS站点是无法AJAX请求非HTTPS的站点的

**Comment by 1409070209** [comment]
那调不了这些接口

**Comment by sky-admin** [comment]
预览机思路不错，提交到git就自动部署到预览机的想法也不错。看一眼Travis吧，也能实现，或者github page我记得可以不启用https的。那个antue项目就是只要合入master，就能在github page上看到最新的效果，不过那个项目不依赖任何后端，是个纯静态的。
